# prometheus.yml
global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s  # Default evaluation interval

scrape_configs:
  # Scrape configuration for your application
  - job_name: 'microservices-monitoring-dashboard'
    scrape_interval: 5s  # Override default scrape interval
    static_configs:
      - targets:
          - 'localhost:8080'  # Your application endpoint with Actuator metrics

  # Scrape configuration for Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'localhost:9090'

  # Scrape configuration for Kubernetes nodes and pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+):(?:\d+);(\d+)
        replacement: $1:$2

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'  # Alertmanager endpoint

rule_files:
  # Load alerting rules from separate files
  - 'alert_rules.yml'

