apiVersion: v1
kind: Service
metadata:
  name: microservices-monitoring-dashboard
  labels:
    app: microservices-monitoring-dashboard
spec:
  selector:
    app: microservices-monitoring-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
